/**
 * scripts/parse-concelhos-md.ts
 *
 * Reads the 18 Markdown files from ~/Desktop/zonas/,
 * parses frontmatter + body + JSON-LD block,
 * and writes src/data/concelhosSEO.ts.
 *
 * Run once:  npx tsx scripts/parse-concelhos-md.ts
 */

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import matter from 'gray-matter'
import { marked } from 'marked'
import os from 'os'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT      = path.resolve(__dirname, '..')
const MD_DIR    = path.join(os.homedir(), 'Desktop', 'zonas')
const OUT_FILE  = path.join(ROOT, 'src', 'data', 'concelhosSEO.ts')

// ── Helpers ──────────────────────────────────────────────────────────────────

function extractJsonLd(raw: string): string {
  // Capture everything between ```html and ``` that contains ld+json
  const match = raw.match(/```html\s*(<script type="application\/ld\+json">[\s\S]*?<\/script>)\s*```/)
  if (!match) return ''
  // Return only the inner JSON-LD script tag content (we'll re-wrap it)
  const inner = match[1].replace(/<script type="application\/ld\+json">/, '').replace(/<\/script>/, '').trim()
  return inner
}

function stripJsonLdBlock(raw: string): string {
  // Remove the entire ## JSON-LD section and everything after it
  return raw.replace(/\n---\n\n## JSON-LD[\s\S]*$/, '').replace(/\n## JSON-LD[\s\S]*$/, '')
}

function slugFromFrontmatter(slug: string): string {
  // frontmatter has "concelho/lisboa" — we want just "lisboa"
  return slug.replace(/^concelho\//, '')
}

// ── Main ─────────────────────────────────────────────────────────────────────

const files = fs.readdirSync(MD_DIR)
  .filter(f => f.endsWith('.md'))
  .sort()

console.log(`Found ${files.length} MD files.`)

type Entry = {
  slug: string
  title: string
  metaDescription: string
  canonical: string
  lastUpdated: string
  bodyHtml: string
  jsonLd: string
}

const entries: Entry[] = []

for (const file of files) {
  const raw      = fs.readFileSync(path.join(MD_DIR, file), 'utf-8')
  const { data, content } = matter(raw)

  const slug            = slugFromFrontmatter(String(data.slug ?? ''))
  const title           = String(data.title ?? '')
  const metaDescription = String(data.meta_description ?? '')
  const canonical       = String(data.canonical ?? '')

  // Normalize lastUpdated to YYYY-MM-DD regardless of how YAML parsed it
  const rawDate    = data.last_updated
  const lastUpdated = rawDate instanceof Date
    ? rawDate.toISOString().slice(0, 10)
    : String(rawDate ?? '').slice(0, 10)

  const cleanedContent = stripJsonLdBlock(content)
  const fullHtml       = await marked.parse(cleanedContent, { async: false }) as string
  // Strip the leading H1 — the page already has its own H1 (concelho name)
  const bodyHtml       = fullHtml.replace(/^<h1[^>]*>.*?<\/h1>\s*/i, '')
  const jsonLd         = extractJsonLd(content)

  if (!slug) {
    console.warn(`  WARN: no slug in ${file}, skipping.`)
    continue
  }

  entries.push({ slug, title, metaDescription, canonical, lastUpdated, bodyHtml, jsonLd })
  console.log(`  OK  ${slug}`)
}

// ── Emit TypeScript ───────────────────────────────────────────────────────────

const lines: string[] = [
  '// concelhosSEO.ts — AUTO-GENERATED by scripts/parse-concelhos-md.ts',
  '// Do not edit by hand. Re-run the script to regenerate.',
  '',
  'export type ConcelhoSEO = {',
  '  slug: string',
  '  title: string',
  '  metaDescription: string',
  '  canonical: string',
  '  lastUpdated: string',
  '  bodyHtml: string',
  '  jsonLd: string',
  '}',
  '',
  'export const concelhosSEO: ConcelhoSEO[] = [',
]

for (const e of entries) {
  lines.push('  {')
  lines.push(`    slug: ${JSON.stringify(e.slug)},`)
  lines.push(`    title: ${JSON.stringify(e.title)},`)
  lines.push(`    metaDescription: ${JSON.stringify(e.metaDescription)},`)
  lines.push(`    canonical: ${JSON.stringify(e.canonical)},`)
  lines.push(`    lastUpdated: ${JSON.stringify(e.lastUpdated)},`)
  lines.push(`    bodyHtml: ${JSON.stringify(e.bodyHtml)},`)
  lines.push(`    jsonLd: ${JSON.stringify(e.jsonLd)},`)
  lines.push('  },')
}

lines.push(']')
lines.push('')

fs.writeFileSync(OUT_FILE, lines.join('\n'), 'utf-8')
console.log(`\nWrote ${entries.length} entries to ${OUT_FILE}`)
